export const SCRATCH = {
  scratchCardCoverUrl:
    "https://storage.googleapis.com/apollon-assets-dev/bjorg/offers/1/scratch_card_cover.png",
  scratchCardLostUrl:
    "https://storage.googleapis.com/apollon-assets-dev/bjorg/offers/1/scratch_card_lost.png",
  scratchCardWonUrl:
    "https://storage.googleapis.com/apollon-assets-dev/bjorg/offers/1/scratch_card_win.png",
};

export const WHEEL = {
  prize: {
    prizeId: 7,
    label: "2 €",
    illustrationUrl: null,
    wheelIllustrationUrl:
      "https://via.placeholder.com/200x200/DD0000/FFFFFF/?text=2%20€",
    isLost: false,
  },
  wheelPrizes: [
    {
      prizeId: 5,
      label: "0 €",
      illustrationUrl: null,
      wheelIllustrationUrl:
        "https://via.placeholder.com/200x200/DD0000/FFFFFF/?text=0%20€",
      isLost: true,
    },
    {
      prizeId: 6,
      label: "1 €",
      illustrationUrl: null,
      wheelIllustrationUrl:
        "https://via.placeholder.com/200x200/FFFFFF/DD0000/?text=1%20€",
      isLost: false,
    },
    {
      prizeId: 7,
      label: "2 €",
      illustrationUrl: null,
      wheelIllustrationUrl:
        "https://via.placeholder.com/200x200/DD0000/FFFFFF/?text=2%20€",
      isLost: false,
    },
    {
      prizeId: 8,
      label: "5 €",
      illustrationUrl: null,
      wheelIllustrationUrl:
        "https://via.placeholder.com/200x200/FFFFFF/DD0000/?text=5%20€",
      isLost: false,
    },
    {
      prizeId: 9,
      label: "10 €",
      illustrationUrl: null,
      wheelIllustrationUrl:
        "https://via.placeholder.com/200x200/DD0000/FFFFFF/?text=10%20€",
      isLost: false,
    },
    {
      prizeId: 10,
      label: "15 €",
      illustrationUrl: null,
      wheelIllustrationUrl:
        "https://via.placeholder.com/200x200/FFFFFF/DD0000/?text=15%20€",
      isLost: false,
    },
    {
      prizeId: 11,
      label: "20 €",
      illustrationUrl: null,
      wheelIllustrationUrl:
        "https://via.placeholder.com/200x200/DD0000/FFFFFF/?text=20%20€",
      isLost: false,
    },
    {
      prizeId: 12,
      label: "25 €",
      illustrationUrl: null,
      wheelIllustrationUrl:
        "https://via.placeholder.com/200x200/FFFFFF/DD0000/?text=25%20€",
      isLost: false,
    },
  ],
};

export const MENU = {
  menuId: 684,
  categories: [
    {
      categoryId: 162268,
      parentId: null,
      description: "Happy Hours (50cl) de 16h30 à 20h30",
      order: 1,
      enabled: true,
    },
    {
      categoryId: 162269,
      parentId: 162268,
      description: "Bières Blondes",
      order: 1,
      enabled: true,
    },
    {
      categoryId: 162270,
      parentId: 162268,
      description: "Bières Blanches",
      order: 2,
      enabled: true,
    },
    {
      categoryId: 162271,
      parentId: 162268,
      description: "Bières Fruitées",
      order: 3,
      enabled: true,
    },
    {
      categoryId: 162272,
      parentId: 162268,
      description: "Bières Brunes",
      order: 4,
      enabled: true,
    },
    {
      categoryId: 162273,
      parentId: 162268,
      description: "Bières Chelous (Berliner Weisse, Gose, Gueuze, Sour…)",
      order: 5,
      enabled: true,
    },
    {
      categoryId: 162277,
      parentId: 162268,
      description: "Pale Ale, IPA, NEIPA ...",
      order: 9,
      enabled: true,
    },
    {
      categoryId: 162278,
      parentId: 162268,
      description: "Bières Ambrées",
      order: 10,
      enabled: true,
    },
    {
      categoryId: 162279,
      parentId: null,
      description: "Carte des Bières",
      order: 2,
      enabled: true,
    },
    {
      categoryId: 162280,
      parentId: 162279,
      description: "Bières Blondes",
      order: 1,
      enabled: true,
    },
    {
      categoryId: 162281,
      parentId: 162279,
      description: "Bières Blanches",
      order: 2,
      enabled: true,
    },
    {
      categoryId: 162282,
      parentId: 162279,
      description: "Bières Fruitées",
      order: 3,
      enabled: true,
    },
    {
      categoryId: 162283,
      parentId: 162279,
      description: "Bières Brunes",
      order: 4,
      enabled: true,
    },
    {
      categoryId: 162284,
      parentId: 162279,
      description: "Bières Chelous (Berliner Weisse, Gose, Gueuze, Sour…)",
      order: 5,
      enabled: true,
    },
    {
      categoryId: 162288,
      parentId: 162279,
      description: "Pale Ale, IPA, NEIPA ...",
      order: 9,
      enabled: true,
    },
    {
      categoryId: 162289,
      parentId: 162279,
      description: "Bières Ambrées",
      order: 10,
      enabled: true,
    },
    {
      categoryId: 162290,
      parentId: null,
      description: "Carte des Vins",
      order: 3,
      enabled: true,
    },
    {
      categoryId: 162291,
      parentId: 162290,
      description: "Rouges",
      order: 1,
      enabled: true,
    },
    {
      categoryId: 162292,
      parentId: 162290,
      description: "Blancs",
      order: 2,
      enabled: true,
    },
    {
      categoryId: 162293,
      parentId: 162290,
      description: "Bulles",
      order: 3,
      enabled: true,
    },
    {
      categoryId: 162295,
      parentId: null,
      description: "Sodas et Jus de Fruits",
      order: 4,
      enabled: true,
    },
    {
      categoryId: 162296,
      parentId: null,
      description: "Petites Faims",
      order: 5,
      enabled: true,
    },
    {
      categoryId: 162297,
      parentId: 162296,
      description: "Saucissons",
      order: 1,
      enabled: true,
    },
    {
      categoryId: 162298,
      parentId: 162296,
      description: "Planchettes",
      order: 2,
      enabled: true,
    },
    {
      categoryId: 186015,
      parentId: null,
      description: "Bières Bouteilles",
      order: 6,
      enabled: true,
    },
    {
      categoryId: 192394,
      parentId: null,
      description: "Vins Bouteilles",
      order: 7,
      enabled: true,
    },
    {
      categoryId: 192395,
      parentId: 192394,
      description: "Vins Blanc",
      order: 1,
      enabled: true,
    },
    {
      categoryId: 192400,
      parentId: 192394,
      description: "Vins Rouges",
      order: 2,
      enabled: true,
    },
    {
      categoryId: 192401,
      parentId: 192394,
      description: "Vins de Macérations",
      order: 3,
      enabled: true,
    },
    {
      categoryId: 192402,
      parentId: 192394,
      description: "Les Bulles",
      order: 4,
      enabled: true,
    },
    {
      categoryId: 317633,
      parentId: null,
      description: "Bières Canettes (à emporter)",
      order: 8,
      enabled: true,
    },
  ],
  products: [
    {
      productId: 1372323,
      categoryId: 162269,
      label: "Paulaner (4,9%) ",
      description: "Paulaner - Lager Allemande",
      order: 933,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 4,
      price2Label: "1L",
      price2: 7,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372327,
      categoryId: 162269,
      label: "Orange Mécanique (7%)",
      description: "Sainte Cru - Belgian Honey Ale",
      order: 937,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372331,
      categoryId: 162270,
      label: "Weissbier (5%) ",
      description: "Weihenstephaner - Blanche",
      order: 941,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 5.5,
      price2Label: "1L",
      price2: 8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372332,
      categoryId: 162271,
      label: "Bacchus Framboise (5%)",
      description: "Van Honsebrouck - Fruit Beer",
      order: 942,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372345,
      categoryId: 162280,
      label: "Paulaner (4,9%)",
      description: "Paulaner - Lager Allemande",
      order: 0,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 3,
      price2Label: "50cl",
      price2: 6,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372349,
      categoryId: 162280,
      label: "Orange Mécanique (7%)",
      description: "Sainte Cru - Belgian Honey Ale",
      order: 4,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.5,
      price2Label: "50cl",
      price2: 8.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372354,
      categoryId: 162281,
      label: "Weissbier (5%)",
      description: "Weihenstephaner - Blanche",
      order: 964,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 3.8,
      price2Label: "50cl",
      price2: 7.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372355,
      categoryId: 162282,
      label: "Bacchus Framboise (5%)",
      description: "Van Honsebrouck - Fruit Beer",
      order: 965,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.5,
      price2Label: "50cl",
      price2: 8.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372372,
      categoryId: 162291,
      label: "Les Vacances de Mr Merlot 2019",
      description: "Merlot, Bio",
      order: 982,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372373,
      categoryId: 162291,
      label: "Les Vigneaux 2017",
      description: "Grenache. Nature. IGP",
      order: 983,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 3.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372375,
      categoryId: 162291,
      label: "Santenay 2012",
      description: "Bourgogne AOC",
      order: 985,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 7,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372376,
      categoryId: 162291,
      label: "Amethyst 2021",
      description: "65% Grenache, 35% Carignan, Nature",
      order: 986,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 6,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372377,
      categoryId: 162291,
      label: "Mas Amiel",
      description: "Maury. VDF",
      order: 987,
      enabled: true,
      pictogramUrl: null,
      price1Label: "10cl",
      price1: 5.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372378,
      categoryId: 162292,
      label: "Muscat 2018",
      description: "Rolly Gassman",
      order: 988,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 6,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372379,
      categoryId: 162292,
      label: "Bourgogne Hautes Côtes de Beaune 2016",
      description: "Chapuis Nature",
      order: 989,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372381,
      categoryId: 162292,
      label: "''Sand'' ",
      description: "Les Funambules Nature AOC Alsace",
      order: 991,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 6,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372383,
      categoryId: 162293,
      label: "Crémant Gemme - André Rohrer",
      description: "Biodynamie. AOP\n",
      order: 993,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 6,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372385,
      categoryId: 162295,
      label: "Orangina",
      description: null,
      order: 995,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 3,
      price2Label: "Happy Hours",
      price2: 3,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372386,
      categoryId: 162295,
      label: "Coca-Cola",
      description: null,
      order: 996,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 3,
      price2Label: "Happy Hours",
      price2: 2,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372387,
      categoryId: 162295,
      label: "Ice Tea",
      description: null,
      order: 997,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 3,
      price2Label: "Happy Hours",
      price2: 2,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372388,
      categoryId: 162295,
      label: "Limonade",
      description: null,
      order: 998,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 2.2,
      price2Label: "Happy Hours",
      price2: 1,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372389,
      categoryId: 162295,
      label: "Perrier",
      description: null,
      order: 999,
      enabled: true,
      pictogramUrl: null,
      price1Label: "33cl",
      price1: 3,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372390,
      categoryId: 162295,
      label: "Lisbeth Bleue",
      description: null,
      order: 1000,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 3.5,
      price2Label: "Happy Hours",
      price2: 2.8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372392,
      categoryId: 162295,
      label: "Lisbeth Verte",
      description: null,
      order: 1002,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 3.5,
      price2Label: "Happy Hours",
      price2: 2.8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372394,
      categoryId: 162295,
      label: "Diabolo",
      description: null,
      order: 1004,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 2.5,
      price2Label: "Happy Hours",
      price2: 1.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372395,
      categoryId: 162295,
      label: "Sirop à l'eau - Menthe",
      description: null,
      order: 1005,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 2,
      price2Label: "Happy Hours",
      price2: 1,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372396,
      categoryId: 162295,
      label: "Sirop à l'eau - Grenadine",
      description: null,
      order: 1006,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 2,
      price2Label: "Happy Hours",
      price2: 1,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372397,
      categoryId: 162295,
      label: "Sirop à l'eau - Pêche",
      description: null,
      order: 1007,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 2,
      price2Label: "Happy Hours",
      price2: 1,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372398,
      categoryId: 162295,
      label: "Sirop à l'eau - Fraise",
      description: null,
      order: 1008,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 2,
      price2Label: "Happy Hours",
      price2: 1,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372399,
      categoryId: 162295,
      label: "Sirop à l'eau - Citron",
      description: null,
      order: 1009,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 2,
      price2Label: "Happy Hours",
      price2: 1,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372400,
      categoryId: 162295,
      label: "Sirop à l'eau - Violette",
      description: null,
      order: 1010,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 2,
      price2Label: "Happy Hours",
      price2: 1,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372401,
      categoryId: 162295,
      label: "Jus de Fruits",
      description: null,
      order: 1011,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 3,
      price2Label: "Happy Hours",
      price2: 2,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372402,
      categoryId: 162297,
      label: "Cèpes",
      description: "Cochon, Champignon",
      order: 1012,
      enabled: true,
      pictogramUrl: null,
      price1Label: null,
      price1: 6.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372403,
      categoryId: 162297,
      label: "Beaufort",
      description: "Cochon, Fromage",
      order: 1013,
      enabled: true,
      pictogramUrl: null,
      price1Label: null,
      price1: 6.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372404,
      categoryId: 162297,
      label: "Nature",
      description: "Cochon",
      order: 1014,
      enabled: true,
      pictogramUrl: null,
      price1Label: null,
      price1: 6.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372405,
      categoryId: 162298,
      label: "Charcuterie",
      description: null,
      order: 1015,
      enabled: true,
      pictogramUrl: null,
      price1Label: null,
      price1: 11,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372406,
      categoryId: 162298,
      label: "Fromages",
      description: null,
      order: 1016,
      enabled: true,
      pictogramUrl: null,
      price1Label: null,
      price1: 12,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372407,
      categoryId: 162298,
      label: "Mixte",
      description: null,
      order: 1017,
      enabled: true,
      pictogramUrl: null,
      price1Label: null,
      price1: 12,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372408,
      categoryId: 162298,
      label: "XL Mixte",
      description: null,
      order: 1018,
      enabled: true,
      pictogramUrl: null,
      price1Label: null,
      price1: 21,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1372409,
      categoryId: 162298,
      label: "Supplément Pain",
      description: null,
      order: 1019,
      enabled: true,
      pictogramUrl: null,
      price1Label: null,
      price1: 0.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1558348,
      categoryId: 186015,
      label: "Gueuze 100% Lambic Bio 2021 (5%)",
      description: "Cantillon - Gueuze",
      order: 1,
      enabled: true,
      pictogramUrl: null,
      price1Label: "75cl",
      price1: 22,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1558349,
      categoryId: 186015,
      label: "Rosé de Gambrinus 2021 (5%)",
      description: "Cantillon - Gueuze Framboise",
      order: 2,
      enabled: true,
      pictogramUrl: null,
      price1Label: "75cl",
      price1: 28,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1558350,
      categoryId: 186015,
      label: "Kriek 100% Lambic Bio 2021 (5%)",
      description: "Cantillon - Kriek",
      order: 3,
      enabled: true,
      pictogramUrl: null,
      price1Label: "75cl",
      price1: 28,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597026,
      categoryId: 192395,
      label: "Joli Blanc 2019",
      description: "Clos Basté - Sud Ouest - Biologique",
      order: 1,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 18,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597032,
      categoryId: 192395,
      label: "Tout Blanc 2018 - 2019",
      description: "Rietch - Riesling Auxerrois - Nature",
      order: 2,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 1L",
      price1: 28,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597035,
      categoryId: 192395,
      label: "Macon-Village ",
      description: "Valette - Nature",
      order: 3,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 40,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597041,
      categoryId: 192395,
      label: "Petite Fleur 2017",
      description: "Julien Meyer - Muscat - Nature",
      order: 4,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 36,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597043,
      categoryId: 192395,
      label: "Limoux St Marie 2017",
      description: "J.L Denois",
      order: 5,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 35,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597045,
      categoryId: 192395,
      label: "Anjou Sec 2014",
      description: "Le Clos de Juchepie - Nature",
      order: 6,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 38,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597046,
      categoryId: 192395,
      label: "Chapuis Frères 2016",
      description: "Haute Côte de Beaune - Biologique",
      order: 7,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 32,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597047,
      categoryId: 192395,
      label: "Cante Renard - Jajaland",
      description: "P. Pibarot - Languedoc - Nature - VDF",
      order: 8,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 24,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597048,
      categoryId: 192400,
      label: "Morgon 2013",
      description: "Domaine Lapierre - Byodinamie",
      order: 1,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 38,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597049,
      categoryId: 192400,
      label: "Du Bout des Doigts 2017",
      description: "Les Vigneaux - Ardèche - Nature",
      order: 2,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 20,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597050,
      categoryId: 192400,
      label: "Cru-Elles 2015",
      description: "I. Engelvin - Gard - Nature",
      order: 3,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 26,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597051,
      categoryId: 192400,
      label: "Pinot Noir 2017",
      description: "M. Kreydenweiss",
      order: 4,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 28,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597052,
      categoryId: 192400,
      label: "L'Ingenu 2017",
      description: "Ratapoil - Pinot Noir - Nature",
      order: 5,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 40,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597053,
      categoryId: 192400,
      label: "One Shot 2018",
      description: "Ratapoil - Trousseau",
      order: 6,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 35,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597054,
      categoryId: 192400,
      label: "Les Ardilles 2018",
      description: "H.Villemade - Cheverny - Loire",
      order: 7,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 36,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597055,
      categoryId: 192401,
      label: "Pinot Gris 2017",
      description: "Julien Meyer - Nature",
      order: 1,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 36,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597056,
      categoryId: 192401,
      label: "Les Rennes 2015",
      description: "P. Boyat - Nature",
      order: 2,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 38,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597057,
      categoryId: 192401,
      label: "Jurassique 2018",
      description: "Wicky - Nature ",
      order: 3,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 38,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597058,
      categoryId: 192402,
      label: "Barbibulls",
      description: "Maxim Lannay - Auxerrois Viognier - Nature",
      order: 1,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 27,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597059,
      categoryId: 192402,
      label: "Domaine des Terrisses",
      description: "Gaillac - Brut - Cazottes",
      order: 2,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 24,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597060,
      categoryId: 192402,
      label: "Billecart",
      description: "Salmon - Brut Rosé",
      order: 3,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 65,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 1597061,
      categoryId: 192402,
      label: "Crémant Lindenlaub",
      description: "Biodynamie",
      order: 4,
      enabled: true,
      pictogramUrl: null,
      price1Label: "Bouteille 75cl",
      price1: 26,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2245823,
      categoryId: 162269,
      label: "Barbar (8%)",
      description: "Lefebvre - Belgian Strong Ale",
      order: 955,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 4.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2245824,
      categoryId: 162280,
      label: "Barbar (8%)",
      description: "Lefebvre - Belgian Strong Ale",
      order: 14,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.5,
      price2Label: "50cl",
      price2: 8.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2297381,
      categoryId: 162291,
      label: "Palabres",
      description: "Pineau D'Aunis  2020",
      order: 988,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12 cl",
      price1: 5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2351188,
      categoryId: 162269,
      label: "Rulles Estivale (5,2%)",
      description: "Rulles - Belgian Pale Ale",
      order: 960,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2351189,
      categoryId: 162280,
      label: "Rulles Estivale (5,2%)",
      description: "Rulles - Belgian Pale Ale",
      order: 19,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.8,
      price2Label: "50cl",
      price2: 9.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2351190,
      categoryId: 162269,
      label: "Rulles Triple (8,4%)",
      description: "Rulles - Triple",
      order: 961,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2351191,
      categoryId: 162269,
      label: "Rulles 1/3 - 2/3 (?%)",
      description: "Rulles - Grincheux Style",
      order: 962,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2351192,
      categoryId: 162280,
      label: "Rulles Triple (8,4%)",
      description: "Rulles - Triple",
      order: 20,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.8,
      price2Label: "50cl",
      price2: 9.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2351193,
      categoryId: 162280,
      label: "Rulles 1/3-2/3 (?%)",
      description: "Rulles - Grincheux Style",
      order: 21,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.8,
      price2Label: "50cl",
      price2: 9.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2402205,
      categoryId: 317633,
      label: "Easy A (6%)",
      description: "Horizont - American Pale Ale",
      order: 6,
      enabled: true,
      pictogramUrl: null,
      price1Label: "33cl",
      price1: 5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2402206,
      categoryId: 317633,
      label: "Midnight Expresso (6%)",
      description: "Piggy Brewing - Dry Coffee Stout",
      order: 7,
      enabled: true,
      pictogramUrl: null,
      price1Label: "44cl",
      price1: 7.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2833531,
      categoryId: 162292,
      label: 'Mâcon-Lugny "Les Crays" 2018',
      description: "Joseph Drouhin",
      order: 992,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 4,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2838179,
      categoryId: 162292,
      label: "Le Joli Blanc 2019",
      description: "Clos Basté VdP Chardonnay Bio",
      order: 993,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 4.2,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2839116,
      categoryId: 162292,
      label: "Joli Grain 2018",
      description: "Wicky AOP Côtes du Jura , Nature",
      order: 994,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12cl",
      price1: 7,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2975378,
      categoryId: 162278,
      label: "Red Fox IPA (7,7%)",
      description: "Matten - Amber Ale",
      order: 957,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 2975381,
      categoryId: 162289,
      label: "Red Fox IPA (7,7%)",
      description: "Matten - Amber Ale",
      order: 984,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.5,
      price2Label: "50cl",
      price2: 8.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3115424,
      categoryId: 162284,
      label: "Rosé de Gambrinus (5%)",
      description: "Cantillon - Lambic",
      order: 981,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12.5cl",
      price1: 4,
      price2Label: "25cl",
      price2: 8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3163156,
      categoryId: 162273,
      label: "Jam Up The Mash (5,2%)",
      description: "Collective Arts - Dry Hopped Sour",
      order: 956,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl ",
      price1: 6.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3163157,
      categoryId: 162284,
      label: "Jam Up The Mash (5,2%)",
      description: "Collective Arts - Dry Hopped Sour",
      order: 982,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.8,
      price2Label: "50cl",
      price2: 8.8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3236868,
      categoryId: 162272,
      label: "Brune Polaire (6%)",
      description: "Papyllon - Brown Ale",
      order: 3,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3236869,
      categoryId: 162283,
      label: "Brune Polaire (6%)",
      description: "Papyllon - Brown Ale",
      order: 3,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4,
      price2Label: "50cl",
      price2: 8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3293271,
      categoryId: 317633,
      label: "Ay, Carmela ! (9.3%)",
      description: "La Pirata - Imperial IPA",
      order: 8,
      enabled: true,
      pictogramUrl: null,
      price1Label: "33cl",
      price1: 6,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3293272,
      categoryId: 317633,
      label: "Brewers in Flames (8.5%)",
      description: "La Pirata - NEIPA",
      order: 9,
      enabled: true,
      pictogramUrl: null,
      price1Label: "44cl",
      price1: 8.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3293273,
      categoryId: 317633,
      label: "No Way Out (5.38%)",
      description: "La Pirata - Double IPA",
      order: 10,
      enabled: true,
      pictogramUrl: null,
      price1Label: "44cl",
      price1: 8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3298231,
      categoryId: 162277,
      label: "Umbilical Wires (8,4%)",
      description: "Prizm - Double NEIPA",
      order: 1070,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 8.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3298233,
      categoryId: 162288,
      label: "Umbilical Wires (8,4%)",
      description: "Prizm - Double NEIPA",
      order: 1094,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 5.5,
      price2Label: "50cl",
      price2: 10.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3302298,
      categoryId: 162280,
      label: "Saison (7%)",
      description: "La Franche - Saison",
      order: 27,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4,
      price2Label: "50cl",
      price2: 8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3302304,
      categoryId: 162269,
      label: "Saison (7%)",
      description: "La Franche - Saison",
      order: 968,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3324177,
      categoryId: 162288,
      label: "Bordering on Chaos (4.5%)",
      description: "Boundary - Pale Ale",
      order: 1098,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 6,
      price2Label: "50cl",
      price2: 11.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3324180,
      categoryId: 162277,
      label: "Bordering on Chaos (4.5%)",
      description: "Boundary - Pale Ale",
      order: 1074,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 9,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3324185,
      categoryId: 162269,
      label: "Chouffe (8%)",
      description: "Brasserie Achouffe - Triple",
      order: 969,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3338833,
      categoryId: 162284,
      label: "Fry-Day! (5,5%)",
      description:
        "Pulfer - Smoothie Sour (Annanas, Fruit de la Passion, Abricot et Mangue)",
      order: 983,
      enabled: true,
      pictogramUrl: null,
      price1Label: "12,5cl",
      price1: 3.5,
      price2Label: "25cl",
      price2: 7,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3351516,
      categoryId: 162277,
      label: "Link In Bio (8%)",
      description: "Boundary - Double IPA",
      order: 1078,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 10.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3351517,
      categoryId: 162288,
      label: "Link In Bio (8%)",
      description: "Boundary - Double IPA",
      order: 1102,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 6.8,
      price2Label: "50cl",
      price2: 12.8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3375695,
      categoryId: 162277,
      label: "Jam Session (4.8%)",
      description: "Funky Fluid - Session Hazy IPA",
      order: 1079,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 8.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3375697,
      categoryId: 162277,
      label: "Selfish Games (6.2%)",
      description: "Horizont - Strawberry Cheescake Pale Ale",
      order: 1080,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3375698,
      categoryId: 162288,
      label: "Jam Session (4.8%)",
      description: "Funky Fluid - Session Hazy IPA",
      order: 1103,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 5.5,
      price2Label: "50cl",
      price2: 10.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3375699,
      categoryId: 162288,
      label: "Selfish Games (6.2%)",
      description: "Horizont - Strawberry Cheescake Pale Ale",
      order: 1104,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 5,
      price2Label: "50cl",
      price2: 10,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461736,
      categoryId: 162269,
      label: "Red Lion (5.3)",
      description: "Totenhopfen - Kellerbier",
      order: 970,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 6.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461741,
      categoryId: 162269,
      label: "Lux Ale (6.66%)",
      description: "Totenhopfen - Special Bitter",
      order: 971,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl ",
      price1: 6.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461743,
      categoryId: 162273,
      label: "Freyja (4.6%)",
      description: "Rebrew - Berliner Weisse",
      order: 958,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl ",
      price1: 6.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461745,
      categoryId: 162277,
      label: "Waka (5.5%)",
      description: "Rebrew - Milshake IPA",
      order: 1082,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl ",
      price1: 6.8,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461747,
      categoryId: 162272,
      label: "Cognac Barrel (9,5%)",
      description: "La Débauche - Barley Wine",
      order: 4,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl ",
      price1: 7,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461750,
      categoryId: 162280,
      label: "Red Lion (5.3%)",
      description: "Totenhopfen - Kellerbier",
      order: 28,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.8,
      price2Label: "50cl",
      price2: 8.8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461751,
      categoryId: 162280,
      label: "Lux Ale (6.66%)",
      description: "Totenhopfen - Special Bitter",
      order: 29,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.8,
      price2Label: "50cl",
      price2: 8.8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461752,
      categoryId: 162283,
      label: "Cognac Barrel (9,5%)",
      description: "La Débauche - Barley Wine",
      order: 4,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 5,
      price2Label: "50cl",
      price2: 9,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461756,
      categoryId: 162288,
      label: "Waka (5.5%)",
      description: "Rebrew - Milshake IPA",
      order: 1106,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.8,
      price2Label: "50cl",
      price2: 8.8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461757,
      categoryId: 162284,
      label: "Freyja (4.6%)",
      description: "Rebrew - Berliner Weisse ",
      order: 985,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.8,
      price2Label: "50cl",
      price2: 8.8,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461888,
      categoryId: 162270,
      label: "Don Bonnano (7%)",
      description: "Pulfer - Imperial Pastry Hefeweizen",
      order: 942,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 8.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461889,
      categoryId: 162281,
      label: "Don Bonnano (7%)",
      description: "Pulfer - Imperial Pastry Hefeweizen",
      order: 965,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 5.5,
      price2Label: "50cl",
      price2: 10.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461946,
      categoryId: 162277,
      label: "Gentle Bastard (6,5%)",
      description: "Horizont - American IPA",
      order: 1083,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl ",
      price1: 6.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461947,
      categoryId: 162278,
      label: "Vienna Lager (5,5%)",
      description: "Galibot - Vienna Lager",
      order: 958,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl ",
      price1: 6.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461948,
      categoryId: 162288,
      label: "Gentle Bastard (6,5%)",
      description: "Horizont - American IPA",
      order: 1107,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.5,
      price2Label: "50cl",
      price2: 8.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3461949,
      categoryId: 162289,
      label: "Vienna Lager (5,5%)",
      description: "Galibot - Vienna Lager",
      order: 985,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 4.5,
      price2Label: "50cl",
      price2: 8.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3509659,
      categoryId: 162273,
      label: "IPA 18 (6,4%)",
      description: "Collective Arts - American IPA avec Noix de Coco et Citron",
      order: 959,
      enabled: true,
      pictogramUrl: null,
      price1Label: "50cl",
      price1: 8.5,
      price2Label: null,
      price2: null,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
    {
      productId: 3509660,
      categoryId: 162284,
      label: "IPA 18 (6,4%)",
      description: "Collective Arts - American IPA avec Noix de Coco et Citron",
      order: 986,
      enabled: true,
      pictogramUrl: null,
      price1Label: "25cl",
      price1: 5.5,
      price2Label: "50cl",
      price2: 10.5,
      price3Label: null,
      price3: null,
      price4Label: null,
      price4: null,
      price5Label: null,
      price5: null,
    },
  ],
};
